[package]
name = "server"
version = "0.1.0"
authors = ["WEON-Junseop <inggull@naver.com>"]
edition = "2024"
license = ""
repository = "https://github.com/inggull/simple-wasm-project.git"
description = "A simple WebAssembly project"